version: '3'

services:
  strapi:
    container_name: evodim-strapi-azure
    image: evodim/strapi-azure:tmp
    environment:
      - DATABASE_CLIENT=${DATABASE_CLIENT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USERNAME=${DATABASE_USERNAME}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_SSL=${DATABASE_SSL}
    ports:
      - 1337:1337
    volumes:
      - ./app:/srv/app
    restart: always
